### ISSUE TITLE
How to add this to meteor app?

### ISSUE THREAD

**Issue by sferoze** [connorbode/ics.js#3]
Hello,

I added the file `ics.js` and `ics.deps.min.js` into my app and whenever I try var `var cal = ics();` in the console it says ics() is undefined. 

How am I supposed to add this?

**Comment by connorbode** [comment]
if it's undefined then the script isn't being loaded into your app.  not sure how meteor works.

**Comment by sferoze** [comment]
@connorbode Is the only file I need ics.js?

**Comment by connorbode** [comment]
looks like you can pick between `ics.js` and `ics.deps.min.js`.  `ics.deps.min.js` probably contains all the dependencies that are listed in the `README`.  

but yeah, if you open up your console in your web browser & paste the contents of either of those files into the console, then do `test = ics()`, you can play around with the created object.

again, not sure how the meteor build process works but that is probably where the issue lies.

**Comment by connorbode** [comment]
@sferoze any luck?

**Comment by sferoze** [comment]
yup I used jquery getscript, and placed the ics file in my public folder
which serves static files. Now it works :)
